web:
  image: fei_java
  ports:
   - "8000:8000"
  links:
   - redis
   - mysql
redis:
  image: fei_redis
mysql:
  image: fei_mysql:fixed
  volumes:
    - data:/var/lib/mysql:rw
  expose:
    - "3306"
